spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '12xy_King'
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: 'select 1'
      maximum-pool-size: 15
      #测试库连接超时时间过短，需要将存活时间调低
      #连接最大生存时间，连接创建后最大的存活时间，active/idle 时间都算存活时间，跟idle-time不同（使用中的连接不会被移除）
      #max-lifetime需要比idle-timeout大1s以上
      #默认1800000ms，最低30000ms，若低于最低值会被重置为默认值
      max-lifetime: 30000
      #默认600000ms，最低10000ms，若低于最低值会被重置为默认值
      idle-timeout: 20000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 60s

mybatis:
  mapper-locations: classpath:mapper/*.xml

thriftServer:
  port: 9010
  minWorkerThreads: 10
  maxWorkerThreads: 1000


thriftClient:
  host: localhost
  port: 9000
  timeout: 30000


produce:
  increment: 1000
  threshold: 200
  expiretime: 3
  timeout: 10000000

#验证码应用级别的配置
security:
  length: 6
  expireSecond: 60
